# Message Types
MSG_CREATE_ACCOUNT_REQUEST = 1
MSG_CREATE_ACCOUNT_RESPONSE = 2
MSG_LOGIN_REQUEST = 3
MSG_LOGIN_RESPONSE = 4
MSG_DELETE_ACCOUNT_REQUEST = 5
MSG_DELETE_ACCOUNT_RESPONSE = 6
MSG_GET_USERS_REQUEST = 7
MSG_GET_USERS_RESPONSE = 8
MSG_SEND_MESSAGE_REQUEST = 9
MSG_SEND_MESSAGE_RESPONSE = 10
MSG_RECEIVE_MESSAGE = 11
MSG_GET_UNREAD_MESSAGES_REQUEST = 12
MSG_GET_UNREAD_MESSAGES_RESPONSE = 13

MSG_ERROR_RESPONSE = 99

# Error Codes
SUCCESS = 0
ERROR_INVALID_MESSAGE = -1
ERROR_USER_EXISTS = -2
ERROR_INVALID_CREDENTIALS = -3
ERROR_USER_NOT_FOUND = -4
ERROR_SERVER_ERROR = -500

# Messages
MESSAGE_OK = "OK"
MESSAGE_INVALID_MESSAGE = "Invalid message type"
MESSAGE_USER_EXISTS = "User already exists"
MESSAGE_INVALID_CREDENTIALS = "Invalid credentials"
MESSAGE_USER_NOT_FOUND = "User not found"
MESSAGE_SERVER_ERROR = "Internal server error"

# Message Format Mapping
MESSAGE_FORMATS = {
    MSG_CREATE_ACCOUNT_REQUEST: 'CREATE_ACCOUNT_REQUEST',
    MSG_CREATE_ACCOUNT_RESPONSE: 'RESPONSE_FORMAT',
    MSG_LOGIN_REQUEST: 'LOGIN_REQUEST',
    MSG_LOGIN_RESPONSE: 'RESPONSE_FORMAT',
    MSG_DELETE_ACCOUNT_REQUEST: 'DELETE_ACCOUNT_REQUEST',
    MSG_DELETE_ACCOUNT_RESPONSE: 'RESPONSE_FORMAT',
    MSG_ERROR_RESPONSE: 'RESPONSE_FORMAT'
}
